- hosts: webservers
  gather_facts: no
  become: yes
  tasks:
    - name: Transfert du fichier WAR vers le répertoire webapps de Tomcat
      ansible.builtin.copy:
        src: jenkins-demo-app-1.0.0.war
        dest: /opt/tomcat/webapps/jenkins-demo-app-1.0.0.war
        owner: tomcat
        group: tomcat
        mode: '0644'
